spring:
  shardingsphere:
    datasource:
      names: master0,slave1,slave2
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.99.100:8803/test
        username: root
        password: root
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.99.100:8805/test
        username: root
        password: root
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.99.100:8806/test
        username: root
        password: root
#      master1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.99.100:8804/test
#        username: root
#        password: root
#      slave3:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.99.100:8807/test
#        username: root
#        password: root
#      slave4:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.99.100:8808/test
#        username: root
#        password: root
    sharding:
      tables:
        sys_user:
          actual-data-nodes: master0.sys_user$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: sys_user$->{id % 2}
          key-generator:
             column: id
             type: SNOWFLAKE
             props:
               worker:
                 id: 0
      master-slave-rules:
        master0:
          master-data-source-name: master0
          slave-data-source-names: slave1,slave2
#        master1:
#          master-data-source-name: master1
#          slave-data-source-names: slave3,slave4
    props:
      sql:
        show: true
      executor:
        size: 4

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: debug
